# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instance_segm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13instance_segm.proto\"(\n\x0fISOneImgRequest\x12\x15\n\rimg_bgr_bytes\x18\x01 \x01(\x0c\"%\n\rISOneImgReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32\x43\n\x0cInstanceSegm\x12\x33\n\rinfer_one_img\x12\x10.ISOneImgRequest\x1a\x0e.ISOneImgReply\"\x00\x62\x06proto3')



_ISONEIMGREQUEST = DESCRIPTOR.message_types_by_name['ISOneImgRequest']
_ISONEIMGREPLY = DESCRIPTOR.message_types_by_name['ISOneImgReply']
ISOneImgRequest = _reflection.GeneratedProtocolMessageType('ISOneImgRequest', (_message.Message,), {
  'DESCRIPTOR' : _ISONEIMGREQUEST,
  '__module__' : 'instance_segm_pb2'
  # @@protoc_insertion_point(class_scope:ISOneImgRequest)
  })
_sym_db.RegisterMessage(ISOneImgRequest)

ISOneImgReply = _reflection.GeneratedProtocolMessageType('ISOneImgReply', (_message.Message,), {
  'DESCRIPTOR' : _ISONEIMGREPLY,
  '__module__' : 'instance_segm_pb2'
  # @@protoc_insertion_point(class_scope:ISOneImgReply)
  })
_sym_db.RegisterMessage(ISOneImgReply)

_INSTANCESEGM = DESCRIPTOR.services_by_name['InstanceSegm']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ISONEIMGREQUEST._serialized_start=23
  _ISONEIMGREQUEST._serialized_end=63
  _ISONEIMGREPLY._serialized_start=65
  _ISONEIMGREPLY._serialized_end=102
  _INSTANCESEGM._serialized_start=104
  _INSTANCESEGM._serialized_end=171
# @@protoc_insertion_point(module_scope)
