# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2


class CommonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.common_infer = channel.unary_unary(
                '/Common/common_infer',
                request_serializer=common__pb2.CommonRequest.SerializeToString,
                response_deserializer=common__pb2.CommonReply.FromString,
                )


class CommonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def common_infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'common_infer': grpc.unary_unary_rpc_method_handler(
                    servicer.common_infer,
                    request_deserializer=common__pb2.CommonRequest.FromString,
                    response_serializer=common__pb2.CommonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Common', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Common(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def common_infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Common/common_infer',
            common__pb2.CommonRequest.SerializeToString,
            common__pb2.CommonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
