# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"$\n\rCommonRequest\x12\x13\n\x0binput_bytes\x18\x01 \x01(\x0c\"#\n\x0b\x43ommonReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32\x38\n\x06\x43ommon\x12.\n\x0c\x63ommon_infer\x12\x0e.CommonRequest\x1a\x0c.CommonReply\"\x00\x62\x06proto3')



_COMMONREQUEST = DESCRIPTOR.message_types_by_name['CommonRequest']
_COMMONREPLY = DESCRIPTOR.message_types_by_name['CommonReply']
CommonRequest = _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREQUEST,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRequest)
  })
_sym_db.RegisterMessage(CommonRequest)

CommonReply = _reflection.GeneratedProtocolMessageType('CommonReply', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREPLY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:CommonReply)
  })
_sym_db.RegisterMessage(CommonReply)

_COMMON = DESCRIPTOR.services_by_name['Common']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONREQUEST._serialized_start=16
  _COMMONREQUEST._serialized_end=52
  _COMMONREPLY._serialized_start=54
  _COMMONREPLY._serialized_end=89
  _COMMON._serialized_start=91
  _COMMON._serialized_end=147
# @@protoc_insertion_point(module_scope)
