# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sky_segmentation_pb2 as sky__segmentation__pb2


class SkySegmentationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer_one_img = channel.unary_unary(
                '/SkySegmentation/infer_one_img',
                request_serializer=sky__segmentation__pb2.SSOneImgRequest.SerializeToString,
                response_deserializer=sky__segmentation__pb2.SSOneImgReply.FromString,
                )


class SkySegmentationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer_one_img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkySegmentationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer_one_img': grpc.unary_unary_rpc_method_handler(
                    servicer.infer_one_img,
                    request_deserializer=sky__segmentation__pb2.SSOneImgRequest.FromString,
                    response_serializer=sky__segmentation__pb2.SSOneImgReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SkySegmentation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SkySegmentation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer_one_img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SkySegmentation/infer_one_img',
            sky__segmentation__pb2.SSOneImgRequest.SerializeToString,
            sky__segmentation__pb2.SSOneImgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
