# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sky_segmentation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sky_segmentation.proto\"(\n\x0fSSOneImgRequest\x12\x15\n\rimg_bgr_bytes\x18\x01 \x01(\x0c\"%\n\rSSOneImgReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32\x46\n\x0fSkySegmentation\x12\x33\n\rinfer_one_img\x12\x10.SSOneImgRequest\x1a\x0e.SSOneImgReply\"\x00\x62\x06proto3')



_SSONEIMGREQUEST = DESCRIPTOR.message_types_by_name['SSOneImgRequest']
_SSONEIMGREPLY = DESCRIPTOR.message_types_by_name['SSOneImgReply']
SSOneImgRequest = _reflection.GeneratedProtocolMessageType('SSOneImgRequest', (_message.Message,), {
  'DESCRIPTOR' : _SSONEIMGREQUEST,
  '__module__' : 'sky_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:SSOneImgRequest)
  })
_sym_db.RegisterMessage(SSOneImgRequest)

SSOneImgReply = _reflection.GeneratedProtocolMessageType('SSOneImgReply', (_message.Message,), {
  'DESCRIPTOR' : _SSONEIMGREPLY,
  '__module__' : 'sky_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:SSOneImgReply)
  })
_sym_db.RegisterMessage(SSOneImgReply)

_SKYSEGMENTATION = DESCRIPTOR.services_by_name['SkySegmentation']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SSONEIMGREQUEST._serialized_start=26
  _SSONEIMGREQUEST._serialized_end=66
  _SSONEIMGREPLY._serialized_start=68
  _SSONEIMGREPLY._serialized_end=105
  _SKYSEGMENTATION._serialized_start=107
  _SKYSEGMENTATION._serialized_end=177
# @@protoc_insertion_point(module_scope)
