# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import depth_estimation_pb2 as depth__estimation__pb2


class DepthEstimationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer_one_img = channel.unary_unary(
                '/DepthEstimation/infer_one_img',
                request_serializer=depth__estimation__pb2.DEOneImgRequest.SerializeToString,
                response_deserializer=depth__estimation__pb2.DEOneImgReply.FromString,
                )


class DepthEstimationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer_one_img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DepthEstimationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer_one_img': grpc.unary_unary_rpc_method_handler(
                    servicer.infer_one_img,
                    request_deserializer=depth__estimation__pb2.DEOneImgRequest.FromString,
                    response_serializer=depth__estimation__pb2.DEOneImgReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DepthEstimation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DepthEstimation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer_one_img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DepthEstimation/infer_one_img',
            depth__estimation__pb2.DEOneImgRequest.SerializeToString,
            depth__estimation__pb2.DEOneImgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
