# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: depth_estimation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65pth_estimation.proto\"(\n\x0f\x44\x45OneImgRequest\x12\x15\n\rimg_bgr_bytes\x18\x01 \x01(\x0c\"%\n\rDEOneImgReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32\x46\n\x0f\x44\x65pthEstimation\x12\x33\n\rinfer_one_img\x12\x10.DEOneImgRequest\x1a\x0e.DEOneImgReply\"\x00\x62\x06proto3')



_DEONEIMGREQUEST = DESCRIPTOR.message_types_by_name['DEOneImgRequest']
_DEONEIMGREPLY = DESCRIPTOR.message_types_by_name['DEOneImgReply']
DEOneImgRequest = _reflection.GeneratedProtocolMessageType('DEOneImgRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEONEIMGREQUEST,
  '__module__' : 'depth_estimation_pb2'
  # @@protoc_insertion_point(class_scope:DEOneImgRequest)
  })
_sym_db.RegisterMessage(DEOneImgRequest)

DEOneImgReply = _reflection.GeneratedProtocolMessageType('DEOneImgReply', (_message.Message,), {
  'DESCRIPTOR' : _DEONEIMGREPLY,
  '__module__' : 'depth_estimation_pb2'
  # @@protoc_insertion_point(class_scope:DEOneImgReply)
  })
_sym_db.RegisterMessage(DEOneImgReply)

_DEPTHESTIMATION = DESCRIPTOR.services_by_name['DepthEstimation']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEONEIMGREQUEST._serialized_start=26
  _DEONEIMGREQUEST._serialized_end=66
  _DEONEIMGREPLY._serialized_start=68
  _DEONEIMGREPLY._serialized_end=105
  _DEPTHESTIMATION._serialized_start=107
  _DEPTHESTIMATION._serialized_end=177
# @@protoc_insertion_point(module_scope)
