# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diffusion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iffusion.proto\"&\n\x0f\x44OneTextRequest\x12\x13\n\x0binput_bytes\x18\x01 \x01(\x0c\"%\n\rDOneTextReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32\x41\n\tDiffusion\x12\x34\n\x0einfer_one_text\x12\x10.DOneTextRequest\x1a\x0e.DOneTextReply\"\x00\x62\x06proto3')



_DONETEXTREQUEST = DESCRIPTOR.message_types_by_name['DOneTextRequest']
_DONETEXTREPLY = DESCRIPTOR.message_types_by_name['DOneTextReply']
DOneTextRequest = _reflection.GeneratedProtocolMessageType('DOneTextRequest', (_message.Message,), {
  'DESCRIPTOR' : _DONETEXTREQUEST,
  '__module__' : 'diffusion_pb2'
  # @@protoc_insertion_point(class_scope:DOneTextRequest)
  })
_sym_db.RegisterMessage(DOneTextRequest)

DOneTextReply = _reflection.GeneratedProtocolMessageType('DOneTextReply', (_message.Message,), {
  'DESCRIPTOR' : _DONETEXTREPLY,
  '__module__' : 'diffusion_pb2'
  # @@protoc_insertion_point(class_scope:DOneTextReply)
  })
_sym_db.RegisterMessage(DOneTextReply)

_DIFFUSION = DESCRIPTOR.services_by_name['Diffusion']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DONETEXTREQUEST._serialized_start=19
  _DONETEXTREQUEST._serialized_end=57
  _DONETEXTREPLY._serialized_start=59
  _DONETEXTREPLY._serialized_end=96
  _DIFFUSION._serialized_start=98
  _DIFFUSION._serialized_end=163
# @@protoc_insertion_point(module_scope)
