# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salient_object_segm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19salient_object_segm.proto\")\n\x10SOSOneImgRequest\x12\x15\n\rimg_bgr_bytes\x18\x01 \x01(\x0c\"&\n\x0eSOSOneImgReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32J\n\x11SalientObjectSegm\x12\x35\n\rinfer_one_img\x12\x11.SOSOneImgRequest\x1a\x0f.SOSOneImgReply\"\x00\x62\x06proto3')



_SOSONEIMGREQUEST = DESCRIPTOR.message_types_by_name['SOSOneImgRequest']
_SOSONEIMGREPLY = DESCRIPTOR.message_types_by_name['SOSOneImgReply']
SOSOneImgRequest = _reflection.GeneratedProtocolMessageType('SOSOneImgRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOSONEIMGREQUEST,
  '__module__' : 'salient_object_segm_pb2'
  # @@protoc_insertion_point(class_scope:SOSOneImgRequest)
  })
_sym_db.RegisterMessage(SOSOneImgRequest)

SOSOneImgReply = _reflection.GeneratedProtocolMessageType('SOSOneImgReply', (_message.Message,), {
  'DESCRIPTOR' : _SOSONEIMGREPLY,
  '__module__' : 'salient_object_segm_pb2'
  # @@protoc_insertion_point(class_scope:SOSOneImgReply)
  })
_sym_db.RegisterMessage(SOSOneImgReply)

_SALIENTOBJECTSEGM = DESCRIPTOR.services_by_name['SalientObjectSegm']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOSONEIMGREQUEST._serialized_start=29
  _SOSONEIMGREQUEST._serialized_end=70
  _SOSONEIMGREPLY._serialized_start=72
  _SOSONEIMGREPLY._serialized_end=110
  _SALIENTOBJECTSEGM._serialized_start=112
  _SALIENTOBJECTSEGM._serialized_end=186
# @@protoc_insertion_point(module_scope)
