# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import salient_object_segm_pb2 as salient__object__segm__pb2


class SalientObjectSegmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer_one_img = channel.unary_unary(
                '/SalientObjectSegm/infer_one_img',
                request_serializer=salient__object__segm__pb2.SOSOneImgRequest.SerializeToString,
                response_deserializer=salient__object__segm__pb2.SOSOneImgReply.FromString,
                )


class SalientObjectSegmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer_one_img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalientObjectSegmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer_one_img': grpc.unary_unary_rpc_method_handler(
                    servicer.infer_one_img,
                    request_deserializer=salient__object__segm__pb2.SOSOneImgRequest.FromString,
                    response_serializer=salient__object__segm__pb2.SOSOneImgReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SalientObjectSegm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SalientObjectSegm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer_one_img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SalientObjectSegm/infer_one_img',
            salient__object__segm__pb2.SOSOneImgRequest.SerializeToString,
            salient__object__segm__pb2.SOSOneImgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
