# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftranslate.proto\"\'\n\x10TranslateRequest\x12\x13\n\x0binput_bytes\x18\x01 \x01(\x0c\"&\n\x0eTranslateReply\x12\x14\n\x0cresult_bytes\x18\x01 \x01(\x0c\x32:\n\tTranslate\x12-\n\x05infer\x12\x11.TranslateRequest\x1a\x0f.TranslateReply\"\x00\x62\x06proto3')



_TRANSLATEREQUEST = DESCRIPTOR.message_types_by_name['TranslateRequest']
_TRANSLATEREPLY = DESCRIPTOR.message_types_by_name['TranslateReply']
TranslateRequest = _reflection.GeneratedProtocolMessageType('TranslateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEREQUEST,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:TranslateRequest)
  })
_sym_db.RegisterMessage(TranslateRequest)

TranslateReply = _reflection.GeneratedProtocolMessageType('TranslateReply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEREPLY,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:TranslateReply)
  })
_sym_db.RegisterMessage(TranslateReply)

_TRANSLATE = DESCRIPTOR.services_by_name['Translate']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSLATEREQUEST._serialized_start=19
  _TRANSLATEREQUEST._serialized_end=58
  _TRANSLATEREPLY._serialized_start=60
  _TRANSLATEREPLY._serialized_end=98
  _TRANSLATE._serialized_start=100
  _TRANSLATE._serialized_end=158
# @@protoc_insertion_point(module_scope)
